#
# ~/.bashrc
#

# Se não estiver sendo executado de maneira interativa
[[ $- != *i* ]] && return

# Não colocar no histórico comandos duplicados ou que comecem com espaço
HISTCONTROL=ignoreboth

# Aliases personalizados
alias ls='ls --color=auto'

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# String personalizada no prompt
PS1='[\u@\h \W]\$ '

if [ -f /usr/share/git/git-prompt.sh ]; then
  . /usr/share/git/git-prompt.sh
  PS1='[\u@\h \W $(__git_ps1 "(%s)")]\$ '
fi

# Configuração do asdf
if [ -f $HOME/.asdf/asdf.sh ]; then
  . $HOME/.asdf/asdf.sh
  . $HOME/.asdf/completions/asdf.bash
fi

# Variáveis de ambiente do pipenv
export PIPENV_VENV_IN_PROJECT=1
