# Listagem de arquivos e diretórios
alias l='ls -1p --group-directories-first --color=auto'

# Acesso rápido aos diretórios
alias doc='cd ~/Documentos'
alias dow='cd ~/Downloads/'

# Voltar níveis de diretório
alias ..='cd ..'

# Git rápido e fácil
alias g='git'

# Alias para usar o manage.py do Django
alias mng='python $VIRTUAL_ENV/../manage.py'
