config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_git:
    src: config/git
    dst: ~/.config/git
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
profiles:
  arch:
    dotfiles:
    - d_git
    - f_bash_aliases
