config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_git:
    src: config/git
    dst: ~/.config/git
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '755'
  f_profile:
    src: profile
    dst: ~/.profile
  f_user-settings.conf:
    src: local/share/orca/user-settings.conf
    dst: ~/.local/share/orca/user-settings.conf
  f_config:
    src: config/yt-dlp/config
    dst: ~/.config/yt-dlp/config
  f_settings.json:
    src: config/Code/User/settings.json
    dst: ~/.config/Code/User/settings.json
    chmod: '755'
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
profiles:
  arch:
    dotfiles:
    - d_git
    - f_bash_aliases
    - f_bashrc
    - f_profile
    - f_user-settings.conf
    - f_config
    - f_settings.json
    - d_qtile
